import { applyPatch, computePatch, DELETED } from "./shared/src/index.ts";
console.log("DELETED sentinel:", JSON.stringify(DELETED), "length", DELETED.length);
const base = { t: 1, stats: { cpu: { loadPct: 5 }, gpu: { utilPct: 64, tempC: 71 } } };
const patch = JSON.parse(JSON.stringify({ t: 2, stats: { gpu: DELETED } }));
console.log("patch over the wire:", JSON.stringify(patch));
const out = applyPatch(base, patch);
console.log("result:", JSON.stringify(out));
console.log("gpu key present?", "gpu" in out.stats, "| value:", JSON.stringify(out.stats.gpu));
console.log("");
console.log("--- computePatch for a removed gpu ---");
const before = { stats: { cpu: { loadPct: 5 }, gpu: { utilPct: 64 } } };
const after  = { stats: { cpu: { loadPct: 6 } } };
const emitted = computePatch(before, after);
console.log("emitted:", JSON.stringify(emitted));
const rt = applyPatch(before, JSON.parse(JSON.stringify(emitted)));
console.log("round-trip:", JSON.stringify(rt), "| gpu gone?", !("gpu" in rt.stats));
