import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { createLogger } from './log.js';
import { AGENT_VERSION } from './version.js';

const log = createLogger('packaged');

/**
 * Support for running as a single packaged executable.
 *
 * The whole app — Node runtime, agent, and the built web client — is one .exe so
 * that installing it is a double-click rather than a runtime install followed by
 * a folder of loose files. That convenience costs exactly one thing: the client
 * can no longer be served straight off disk, because inside a packaged binary
 * there is no disk to serve from.
 */

interface SeaApi {
  isSea(): boolean;
  getRawAsset(key: string): ArrayBuffer;
}

let cachedSea: SeaApi | null | undefined;

function sea(): SeaApi | null {
  if (cachedSea !== undefined) return cachedSea;
  try {
    // Required lazily and by string so the ESM build never tries to resolve it.
    // `node:sea` exists from Node 20.12 on, but a missing module must degrade to
    // "not packaged" rather than crash the agent.
    const { createRequire } = require('node:module') as typeof import('node:module');
    const req = typeof require === 'function' ? require : createRequire(process.execPath);
    cachedSea = req('node:sea') as SeaApi;
  } catch {
    cachedSea = null;
  }
  return cachedSea;
}

/** True when running from the packaged .exe rather than from a Node install. */
export function isPackaged(): boolean {
  try {
    return sea()?.isSea() === true;
  } catch {
    return false;
  }
}

/**
 * Reads a file embedded in the packaged executable.
 *
 * Returns undefined when not packaged or when the asset is absent, so callers
 * can fall back to reading the same file off disk during development.
 */
export function readAsset(key: string): Buffer | undefined {
  const api = sea();
  if (!api?.isSea()) return undefined;
  try {
    return Buffer.from(api.getRawAsset(key));
  } catch {
    return undefined;
  }
}

/** Key of the asset listing every other asset, written by the dist script. */
const MANIFEST_KEY = 'client-manifest.json';

/**
 * Unpacks the embedded client to a real directory and returns its path.
 *
 * Serving from memory instead would avoid the disk write, but `@fastify/static`
 * — and the range requests, conditional GETs and correct MIME types that come
 * with it — wants a directory. Writing ~3.6 MB once at first launch buys all of
 * that for free, and every launch afterwards reuses it.
 *
 * Returns undefined when not packaged, or on any failure: the caller then falls
 * back to the normal on-disk search, which is what a developer build wants.
 */
export function extractClient(): string | undefined {
  const api = sea();
  if (!api?.isSea()) return undefined;

  let manifest: string[];
  try {
    manifest = JSON.parse(Buffer.from(api.getRawAsset(MANIFEST_KEY)).toString('utf8')) as string[];
  } catch (err) {
    log.error(`packaged client manifest is unreadable: ${(err as Error).message}`);
    return undefined;
  }

  /**
   * Version alone would not force a re-extract during development, when the
   * version is unchanged but the client is not, so the directory name also
   * carries a hash of the file list.
   */
  const stamp = createHash('sha256').update(manifest.join('\n')).digest('hex').slice(0, 12);
  const dir = path.join(
    process.env['LOCALAPPDATA'] ?? os.tmpdir(),
    'PCRemote',
    `client-${AGENT_VERSION}-${stamp}`,
  );

  // Already unpacked by an earlier launch. The marker is written last, so its
  // presence means the previous extraction ran to completion.
  const marker = path.join(dir, '.complete');
  try {
    if (fs.statSync(marker).isFile()) return dir;
  } catch {
    // Not extracted yet.
  }

  try {
    for (const key of manifest) {
      // Keys are relative and generated by the build, but they end up in a
      // filesystem path, so a traversal must not be possible even if the blob
      // were tampered with.
      const target = path.resolve(dir, key);
      if (target !== dir && !target.startsWith(dir + path.sep)) {
        log.warn(`skipping suspicious asset path: ${key}`);
        continue;
      }
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, Buffer.from(api.getRawAsset(key)));
    }
    fs.writeFileSync(marker, new Date().toISOString(), 'utf8');
  } catch (err) {
    log.error(`could not unpack the client: ${(err as Error).message}`);
    return undefined;
  }

  log.debug(`unpacked ${manifest.length} client files to ${dir}`);
  return dir;
}
